name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main # Este workflow será acionado sempre que houver um push para a branch 'main'

env:
  AWS_REGION: us-east-2
  ECR_REPOSITORY: telegram-bot-php-repo
  AWS_ACCOUNT_ID: 597088015325 # Seu ID de conta AWS

jobs:
  build-and-push:
    runs-on: ubuntu-latest # O tipo de ambiente virtual para rodar o job

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Clona seu repositório GitHub

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # Usa o segredo que você criou
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # Usa o segredo que você criou
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: docker/login-action@v3
      with:
        registry: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com

    - name: Build and Push Docker image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
