name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main # Este workflow será acionado sempre que houver um push para a branch 'main'

env:
  AWS_REGION: us-east-2
  ECR_REPOSITORY: telegram-bot-php-repo
  AWS_ACCOUNT_ID: 597088015325 # Seu ID de conta AWS
  IMAGE_TAG: latest # Definir a tag aqui globalmente para fácil acesso

jobs:
  build-and-push:
    runs-on: ubuntu-latest # O tipo de ambiente virtual para rodar o job

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Clona seu repositório GitHub

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # Usa o segredo que você criou
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # Usa o segredo que você criou
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: docker/login-action@v3
      with:
        # A URL do registro é formada diretamente aqui usando as variáveis de ambiente globais
        registry: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com

    - name: Build and Push Docker image
      run: |
        # Definir a URL completa do registro ECR para uso direto nos comandos docker
        # Isso garante que a string seja formada corretamente antes de ser passada
        ECR_REGISTRY_URL="${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com"
        
        # Construir a imagem Docker com a tag completa e correta
        # O $ECR_REGISTRY_URL garante que não haverá uma barra inicial desnecessária
        docker build -t "$ECR_REGISTRY_URL/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}" .
        
        # Enviar a imagem para o ECR
        docker push "$ECR_REGISTRY_URL/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}"
